//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace vrmmo
{
	public class Entity
	{
		public float x = 0;
		public float y = 0;
        public float vx = 0;
        public float vy = 0;
		public UInt16 id = 0;
        public UInt16 graphic = 0;
        public float upDown = 0;
        public float leftRight = 0;
        public float tilt = 0;
		public Entity ()
		{
		}
	}
}

